version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-name: react-data-table-component*
  - dependency-name: styled-components
  ignore:
  - dependency-name: reactjs-popup
    versions:
    - 2.0.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@formatjs/intl-relativetimeformat"
    versions:
    - 8.0.4
    - 8.0.5
    - 8.0.6
    - 8.1.0
    - 8.1.2
    - 8.1.3
    - 8.1.4
    - 8.1.5
    - 8.1.6
  - dependency-name: react-tooltip
    versions:
    - 4.2.14
    - 4.2.15
    - 4.2.16
    - 4.2.17
    - 4.2.18
  - dependency-name: react-redux
    versions:
    - 7.2.3
    - 7.2.4
  - dependency-name: redux
    versions:
    - 4.1.0
  - dependency-name: react-datepicker
    versions:
    - 3.6.0
    - 3.8.0
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.6
  - dependency-name: date-fns
    versions:
    - 2.20.0
    - 2.20.1
    - 2.21.0
    - 2.21.1
  - dependency-name: workbox-expiration
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.5
  - dependency-name: msw
    versions:
    - 0.27.0
    - 0.27.2
    - 0.28.0
    - 0.28.1
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.1.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
    - 11.2.6
  - dependency-name: react-dropzone
    versions:
    - 11.3.0
    - 11.3.1
    - 11.3.2
  - dependency-name: use-query-params
    versions:
    - 1.2.1
    - 1.2.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: react-final-form
    versions:
    - 6.5.3
  - dependency-name: workbox-routing
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-core
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-recipes
    versions:
    - 6.1.2
  - dependency-name: workbox-strategies
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: workbox-precaching
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@hotosm/iso-countries-languages"
    versions:
    - 1.1.0
  - dependency-name: slug
    versions:
    - 4.0.3
  - dependency-name: react-scripts
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: react-select
    versions:
    - 4.1.0
  - dependency-name: react-placeholder
    versions:
    - 4.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: "@formatjs/intl-pluralrules"
    versions:
    - 4.0.10
    - 4.0.6
    - 4.0.7
    - 4.0.8
    - 4.0.9
  - dependency-name: "@mapbox/mapbox-gl-draw"
    versions:
    - 1.2.0
    - 1.2.1
    - 1.2.2
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
  - dependency-name: jest-canvas-mock
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: "@mapbox/geo-viewport"
    versions:
    - 0.4.1
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: dompurify
    versions:
    - 2.2.6
  - dependency-name: mapbox-gl-draw-circle
    versions:
    - 1.1.2
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
  - dependency-name: alembic
    versions:
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: sentry-sdk[flask]
    versions:
    - 0.20.3
  - dependency-name: greenlet
    versions:
    - 1.0.0
  - dependency-name: gevent
    versions:
    - 21.1.2
  - dependency-name: oauthlib
    versions:
    - 3.1.0
  - dependency-name: bleach
    versions:
    - 3.3.0
  - dependency-name: flask-oauthlib
    versions:
    - 0.9.6
  - dependency-name: flask-cors
    versions:
    - 3.0.10
  - dependency-name: attrs
    versions:
    - 20.3.0
  - dependency-name: werkzeug
    versions:
    - 1.0.1
  - dependency-name: black
    versions:
    - 20.8b1
  - dependency-name: geojson
    versions:
    - 2.5.0
