version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_name: "react-data-table-component*"
      - match:
          dependency_name: "react-datepicker"
      - match:
          dependency_name: "styled-components"

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
